# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bellboardId', models.CharField(max_length=10)),
                ('association', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('method', models.CharField(max_length=100)),
                ('changes', models.IntegerField()),
                ('composer', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dedication', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('tenor', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ringer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RingerPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bell', models.CharField(max_length=10)),
                ('conductor', models.BooleanField()),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Performance')),
                ('ringer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Ringer')),
            ],
        ),
        migrations.CreateModel(
            name='RingingName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ringer',
            name='ringingname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.RingingName'),
        ),
        migrations.AddField(
            model_name='performance',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Place'),
        ),
        migrations.AddField(
            model_name='footnote',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Performance'),
        ),
    ]
