# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='method',
            field=models.CharField(max_length=1000),
        ),
    ]
